# Generated by Django 4.2.4 on 2024-02-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='text',
            new_name='chocie',
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='question',
            new_name='question_choice',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='text',
            new_name='question',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='point',
        ),
        migrations.AddField(
            model_name='question',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
