# Generated by Django 4.2.4 on 2024-02-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_useraccount_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='currect_quiz',
            field=models.IntegerField(default=0),
        ),
    ]
