# Generated by Django 4.2.4 on 2024-02-28 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_useraccount_currect_quiz'),
        ('history', '0002_alter_quiz_history_currect_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.useraccount'),
        ),
    ]
