# Generated by Django 4.2.4 on 2024-02-28 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0006_quiz_history_user_account_alter_quiz_history_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz_history',
            name='user_account',
        ),
    ]
