# Generated by Django 4.2.4 on 2024-02-29 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizs', '0003_alter_review_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='Name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
