# Generated by Django 4.2.4 on 2024-03-01 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizs', '0004_review_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='quizs.quiz'),
        ),
    ]
